### ISSUE TITLE
Error: open stream failed after setup step 3

### ISSUE THREAD

**Issue by ptr2null** [neos/neos-setup#7]
### Description

In Neos Setup Step 3 we're asked to give some information about our site and site-package.
After that it throws a fatal error.

#### Actual behavior

```
Warning: Uncaught Neos\Flow\Error\Exception: Warning: require(C:/xampp/htdocs/ohm-xpcd/Data/Temporary/Development/Doctrine/Proxies\__CG__NeosContentRepositoryDomainModelNodeData.php): failed to open stream: No such file or directory in C:\xampp\htdocs\ohm-xpcd\Packages\Libraries\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php line 204 in C:\xampp\htdocs\ohm-xpcd\Packages\Framework\Neos.Flow\Classes\Error\ErrorHandler.php:81 Stack trace: #0 C:\xampp\htdocs\ohm-xpcd\Packages\Libraries\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php(204): Neos\Flow\Error\ErrorHandler->handleError(2, 'require(C:/xamp...', 'C:\\xampp\\htdocs...', 204, Array) neos/neos-ui#1 C:\xampp\htdocs\ohm-xpcd\Packages\Libraries\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php(204): require() neos/neos-ui#2 C:\xampp\htdocs\ohm-xpcd\Packages\Libraries\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php(114): Doctrine\Common\Proxy\AbstractProxyFactory->getProxyDefinition('Neos\\ContentRep...') neos/neos-ui#3 C:\xampp\ht in C:\xampp\htdocs\ohm-xpcd\Packages\Framework\Neos.Flow\Classes\Error\ErrorHandler.php on line 81

Fatal error: Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required 'C:/xampp/htdocs/ohm-xpcd/Data/Temporary/Development/Doctrine/Proxies\__CG__NeosContentRepositoryDomainModelNodeData.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\ohm-xpcd\Packages\Libraries\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php on line 204
```
### Affected Versions

Neos: 5.3.0 (installed with composer, latest version)
PHP: 7.3.23
UI: N/A

Is this a bug?

Regards,
Markus

**Comment by mhsdesign** [comment]
With the version 3 we completely rewrote the setup. This will not be an issue anymore ;)
